### ISSUE TITLE
code misstake

### ISSUE THREAD

**Issue by OZOAR** [nife8975/Antminer_Status_Monitor#1] opened 2018-08-16 19:27 UTC
method monitorAntminerStatus. Local variable api_command not exists.
check that  59th line.
s.send(json.dumps({"command":api_command[0]}).encode('utf-8'))

**Comment by nife8975** [comment] 2018-08-16 21:32
Hi OZOAR,

Thanks for reporting this issue. I have just pushed a fix but I do not have access to an Antminer right now to test it out. Please pull the recent changed and confirm that the issue is fixed.

**Closed as completed** 2018-11-05 20:01 UTC
